name = "100apps-template"
compatibility_date = "2026-01-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "100games"
database_id = "cb90aeb2-0985-441f-b171-29722298690b"